vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        suppliers:
            uri_prefix: /images/suppliers
            upload_destination: '%kernel.project_dir%/public/images/suppliers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
